version: '3'

services:

  nginx:
    image: nginx
    ports: 
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
    - sawatzky_back_dev_static:/home/sawatzky_back_dev/back/staticfiles
    - sawatzky_back_dev_media:/home/sawatzky_back_dev/back/media
    - ./build_dev:/home/sawatzky_back_dev

    - sawatzky_back_prod_static:/home/sawatzky_back_prod/back/staticfiles
    - sawatzky_back_prod_media:/home/sawatzky_back_prod/back/media
    - ./build_prod:/home/sawatzky_back_prod

    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # - certbot_data:/var/www/certbot

    # depends_on:
    #   - certbot
    networks:
      - app-network

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email msheverdin648@gmail.com --agree-tos --no-eff-email -d SW-dev.uitdep.ru -d Sw-prod.uitdep.ru --staging --dry-run
  #   networks:
  #     - app-network

  redis:
      image: redis:latest
      ports:
        - 6379:6379
      networks:
        - app-network


volumes:
  sawatzky_back_dev_static:
    external: true
  sawatzky_back_dev_media:
    external: true
  sawatzky_back_prod_static:
    external: true
  sawatzky_back_prod_media:
    external: true
  # certbot_data:

networks:
  app-network:
    external: true
