# Generated by Django 4.1 on 2024-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_workobject_address_alter_workobject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание заявки'),
        ),
    ]
