# Generated by Django 4.1 on 2024-02-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='prepayment',
            field=models.BooleanField(blank=True, default=False, verbose_name='Работа по предоплате'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус контрагента'),
        ),
    ]
