# Generated by Django 4.1 on 2024-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_legalentity_prepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Срочно'), ('notUrgent', 'Не срочно')], default='urgent', max_length=20, verbose_name='Приоритет'),
        ),
    ]
