# Generated by Django 4.1 on 2024-02-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_report_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='requisites',
            field=models.FileField(blank=True, default=1, null=True, upload_to='requisites/', verbose_name='Файл реквизита'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус отчета'),
        ),
    ]
