# Generated by Django 4.1 on 2024-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_report_description_report_requisites_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='report',
            name='how_created',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Как создан'),
        ),
        migrations.AlterField(
            model_name='report',
            name='requisites',
            field=models.FileField(blank=True, default=1, null=True, upload_to='requisites/', verbose_name='Реквизит'),
        ),
    ]
