# Generated by Django 4.1 on 2024-02-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_report_created_report_how_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='requisites',
            field=models.FileField(blank=True, null=True, upload_to='requisites/', verbose_name='Реквизит'),
        ),
    ]
