# Generated by Django 4.1 on 2024-02-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_report_requisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created',
        ),
        migrations.RemoveField(
            model_name='report',
            name='how_created',
        ),
        migrations.AlterField(
            model_name='report',
            name='createdAt',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
