# Generated by Django 4.1 on 2024-02-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_report_requisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='requisites',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Реквизиты'),
        ),
    ]
