# Generated by Django 4.1 on 2024-02-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_report_requisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='requisites',
        ),
    ]
