# Generated by Django 4.1 on 2024-02-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_report_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sawatzkyemployee', verbose_name='Сотрудник, создавший отчет'),
        ),
    ]
