# Generated by Django 4.1 on 2024-02-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_report_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='workObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workobject', verbose_name='Рабочий объект'),
        ),
        migrations.AddField(
            model_name='report',
            name='workObjectsGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workobjectsgroup', verbose_name='Группа рабочих объектов'),
        ),
    ]
