# Generated by Django 4.1 on 2024-03-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_report_workobject_report_workobjectsgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='prepayment',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Работа по предоплате'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус контрагента'),
        ),
    ]
