# Generated by Django 4.1 on 2024-03-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_legalentity_prepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='workObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workobject', verbose_name='Рабочий объект'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('initiator', 'Инициатор'), ('dispatcher', 'Диспетчер')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
