# Generated by Django 4.1 on 2024-03-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_application_workobject_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='workObject',
        ),
    ]
