# Generated by Django 4.1 on 2024-03-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_application_workobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='powerOfAttorneyNumber',
        ),
        migrations.AddField(
            model_name='employee',
            name='powerOfAttorney',
            field=models.FileField(blank=True, default=None, null=True, upload_to='power_of_attorneys', verbose_name='Доверенность'),
        ),
    ]
