# Generated by Django 4.1 on 2024-03-11 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_employee_powerofattorneynumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatChange', models.CharField(max_length=300, verbose_name='Какое изменении')),
                ('changeDate', models.DateField(auto_now_add=True, verbose_name='Дата изменения заявки')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application', verbose_name='Заявка')),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='api.comments', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='application',
            name='sawatzkyComments',
            field=models.ManyToManyField(blank=True, null=True, related_name='sawatzkyComments', to='api.comments', verbose_name='Комментарии пользователей Sawatzky'),
        ),
    ]
