# Generated by Django 4.1 on 2024-03-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_log_comments_application_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='application_comments', to='api.comments', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sawatzkyComments',
            field=models.ManyToManyField(blank=True, null=True, related_name='application_sawatzky', to='api.comments', verbose_name='Комментарии пользователей Sawatzky'),
        ),
    ]
