# Generated by Django 4.1 on 2024-03-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_application_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='application',
        ),
    ]
