# Generated by Django 4.1 on 2024-03-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_log_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='logs',
            field=models.ManyToManyField(blank=True, null=True, related_name='application_logs', to='api.log', verbose_name='Журнал'),
        ),
    ]
