# Generated by Django 4.1 on 2024-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_application_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='application',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='api.application', verbose_name='Заявка'),
            preserve_default=False,
        ),
    ]
