# Generated by Django 4.1 on 2024-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_log_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='changeDate',
        ),
        migrations.AddField(
            model_name='log',
            name='changeDateTime',
            field=models.DateTimeField(null=True, verbose_name='Дата изменения заявки'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docType',
            field=models.CharField(choices=[('act', 'Акт'), ('powerOfAttorney', 'Доверенность'), ('paymentSlip', 'Платежка'), ('other', 'Прочее'), ('confirmation', 'Подтверждение')], max_length=32, verbose_name='Тип документа'),
        ),
    ]
