# Generated by Django 4.1 on 2024-04-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_log_changedate_log_changedatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='changeDateTime',
            new_name='changeDate',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Создана'), ('processed', 'Обрабатывается'), ('coordination', 'На согласовании у заказчика'), ('paymentCoordination', 'Ожидается оплата'), ('inWork', 'Передано исполнителю'), ('waitingFinish', 'Ожидает подтверждения завершения'), ('finished', 'Выполнено'), ('rejected', 'Отклонена')], default='new', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='workmaterial',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус материала'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус услуги'),
        ),
    ]
