# Generated by Django 4.1 on 2024-04-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_rename_changedatetime_log_changedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sawatzkyemployee',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
