# Generated by Django 4.1 on 2024-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_employee_status_alter_sawatzkyemployee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Статус контрагента'),
        ),
    ]
