# Generated by Django 4.1 on 2024-04-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_legalentity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, related_name='application_documents', to='api.document', verbose_name='Документы'),
        ),
    ]
