# Generated by Django 4.1 on 2024-04-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_application_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='client',
            new_name='legalEntity',
        ),
    ]
