# Generated by Django 4.1 on 2024-04-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_rename_client_report_legalentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='actualWorkDate',
            field=models.DateField(default='2024-04-24', verbose_name='Фактическая дата выполнения запроса'),
            preserve_default=False,
        ),
    ]
