# Generated by Django 4.1 on 2024-04-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_application_actualworkdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='actualWorkDate',
        ),
    ]
