# Generated by Django 4.1 on 2024-04-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_application_actualworkdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='actualWorkDate',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата выполнения запроса'),
        ),
    ]
