# Generated by Django 4.1 on 2024-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_application_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='НДС'),
        ),
    ]
