# Generated by Django 4.1 on 2024-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_application_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс'),
        ),
    ]
