# Generated by Django 4.1 on 2024-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_legalentity_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='application_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус заявки'),
        ),
    ]
