# Generated by Django 4.1 on 2024-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_legalentity_totalinvoicedsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок заявки'),
        ),
    ]
