# Generated by Django 4.1 on 2024-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_application_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование документа'),
        ),
    ]
