# Generated by Django 4.1 on 2024-06-12 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_alter_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDocumentNumber', models.CharField(max_length=100, verbose_name='Номер платежного документа')),
                ('receiptDate', models.DateField(verbose_name='Дата поступления')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая сумма')),
                ('amountByInvoices', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма по счетам')),
                ('legalEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.legalentity', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Генеральный журнал',
                'verbose_name_plural': 'Генеральные журналы',
            },
        ),
    ]
