# Generated by Django 4.1 on 2024-06-12 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_generaljournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='generalJournal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.generaljournal', verbose_name='Генеральный журнал'),
        ),
    ]
