# Generated by Django 4.1 on 2024-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_application_generaljournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaljournal',
            name='status',
            field=models.CharField(choices=[('fully', 'Полностью'), ('partially', 'Частично'), ('unpaid', 'Неоплаченная')], default='new', max_length=50, verbose_name='Статус оплаты'),
        ),
    ]
