# Generated by Django 4.1 on 2024-06-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_generaljournal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='generalJournal',
        ),
        migrations.AddField(
            model_name='generaljournal',
            name='application',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.application', verbose_name='Заявка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='status',
            field=models.CharField(choices=[('fully', 'Полностью'), ('partially', 'Частично'), ('unpaid', 'Неоплаченная')], default='unpaid', max_length=50, verbose_name='Статус оплаты'),
        ),
    ]
