# Generated by Django 4.1 on 2024-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_remove_application_generaljournal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaljournal',
            name='totalDebt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма долга'),
        ),
        migrations.AddField(
            model_name='generaljournal',
            name='totalPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
