# Generated by Django 4.1 on 2024-06-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_generaljournal_totaldebt_generaljournal_totalpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaljournal',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.application', verbose_name='Заявка'),
        ),
    ]
