# Generated by Django 4.1 on 2024-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_generaljournal_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='mail',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='settlementAccount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расчётный счёт'),
        ),
    ]
