# Generated by Django 4.1 on 2024-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_alter_legalentity_bank_alter_legalentity_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='correspondentAccount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Корреспондентский счёт'),
        ),
    ]
