# Generated by Django 4.1 on 2024-06-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_application_totalpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaljournal',
            name='application',
        ),
        migrations.AddField(
            model_name='generaljournal',
            name='applications',
            field=models.ManyToManyField(blank=True, to='api.application', verbose_name='Заявки'),
        ),
    ]
