# Generated by Django 4.1 on 2024-06-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_remove_generaljournal_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaljournal',
            old_name='applications',
            new_name='application',
        ),
    ]
