# Generated by Django 4.1 on 2024-06-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_rename_applications_generaljournal_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='totalDebt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма долга'),
        ),
    ]
