# Generated by Django 4.1 on 2024-06-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_application_totaldebt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='totalDebt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма долга'),
        ),
        migrations.AlterField(
            model_name='application',
            name='totalPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
