# Generated by Django 4.1 on 2024-06-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_alter_application_totaldebt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='totalSum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Общая стоимость работ'),
        ),
    ]
