# Generated by Django 4.1 on 2024-06-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_alter_application_totalsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='legalEntity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.legalentity', verbose_name='Заказчик в рамках которого создается отчет'),
        ),
    ]
