# Generated by Django 4.1 on 2024-06-22 21:25

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_alter_report_legalentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPayment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма оплаты')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('general_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generaljournal')),
            ],
        ),
        migrations.AddField(
            model_name='generaljournal',
            name='new_application',
            field=models.ManyToManyField(blank=True, through='api.ApplicationJournal', to='api.application', verbose_name='Новые заявки'),
        ),
    ]
