# Generated by Django 4.1 on 2024-06-22 21:42

from django.db import migrations, models


def copy_m2m_data(apps, schema_editor):
    GeneralJournal = apps.get_model('api', 'GeneralJournal')
    for general_journal in GeneralJournal.objects.all():
        for application in general_journal.application.all():
            general_journal.new_application.add(application)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_applicationjournal_alter_generaljournal_application_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_m2m_data),
    ]
