# Generated by Django 4.1 on 2024-06-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_remove_generaljournal_new_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaljournal',
            name='application',
        ),
    ]
