# Generated by Django 4.1 on 2024-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_remove_generaljournal_new_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaljournal',
            name='new_application',
        ),
        migrations.AddField(
            model_name='generaljournal',
            name='application',
            field=models.ManyToManyField(blank=True, through='api.ApplicationJournal', to='api.application', verbose_name='Заявки'),
        ),
    ]
