# Generated by Django 4.1 on 2024-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_remove_generaljournal_new_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationjournal',
            name='totalDebt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма долга'),
        ),
    ]
