# Generated by Django 4.1 on 2024-06-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_applicationjournal_totaldebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.employee', verbose_name='Заказчики'),
        ),
        migrations.AddField(
            model_name='application',
            name='legalEntities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.legalentity', verbose_name='Юридические лица'),
        ),
    ]
