# Generated by Django 4.1 on 2024-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_application_clients_application_legalentities'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='totalAmountOfDebt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма задолженности'),
        ),
    ]
