# Generated by Django 4.1 on 2024-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_legalentity_totalamountofdebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='overdueInvoicesPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент просроченных счетов'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='paidInvoicesPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент оплаченных счетов'),
        ),
    ]
